### ISSUE TITLE
better usage /display ideas for gas turbine generator

### ISSUE THREAD

**Issue by Mementh** [bdew-minecraft/bdlib#23]
I would like to see one or two changes to how the gas turbine generators work.
1. don't store power.. it currently is made on demand in the max of 25k chunks.  why not just have it run to give power on demand/pull? ( is there a reason to have storage options to allow it to pull power? ) 
   this might make the storage modules worth using vs other power storage options. 
2. a option to see average usage of a fuel from the last few hours? since the system currently does not run based on usage it will spike up and down randomly so seeing how much your using in fuel is very hard to quantify. a graph or just numbers would be nice. ( maybe a option to see last minute 30 mins hour 6 hours and 24 hours?

**Comment by bdew** [comment]
Internal storage exists in pretty much every power-producer in minecraft, at least in all the mainstream power systems. I think removing it would just confuse users which expect it.

It's also not that easy in terms of code, considering i'm currently supporting 2 very different power systems, and intend to add more in the future. Right now RF implementation is purely push-based and IC2 is in theory pull-based, but uses a hybrid implementation because of bugs in the energy net.

I'll consider adding a bigger average window, but i think hour or day is way too long to be useful to most players. Once i get ComputerCraft/OpenComputers support done those who want longer term monitoring will be able to do it  themselves.

Also this is the wrong place to post this. Actual issues with Advanced Generators should go here - https://github.com/bdew/generators/issues, and general discussion of mechanics (and changing them) are probably better off in the forum thread.

**Comment by Mementh** [comment]
thanks :)
